---
title: "Get Word Frequency from CHILDES and AoA from Wordbank"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(childesr)
library(wordbankr)
library(here)
```

## Read Concepts

```{r}
vrd_nouns <- read_csv(here("data/concepts/vrd_noun_concept_least10_single_word.txt"),
                     show_col_types = FALSE,
                     col_names = "synset") %>%
  separate(synset, into = c("word", "n", "set"), sep = "\\.", 
           remove = FALSE) %>%
  select(-n)

vrd_verbs <- read_csv(here("data/concepts/vrd_verb_concept_least10_single_word.txt"),
                     show_col_types = FALSE,
                     col_names = "synset") %>%
  separate(synset, into = c("word", "n", "set"), sep = "\\.", 
           remove = FALSE) %>%
  select(-n)
```

## Get word frequency

```{r read-childes noun} 
noun_freq <- map_dfr(pull(vrd_nouns, word),
        ~get_types(collection = c("Eng-NA", "Eng-UK"), 
                   role_exclude = "Target_Child", 
                                  type = .x)) %>%
  mutate(gloss = tolower(gloss)) %>%
  group_by(gloss) %>%
  summarise(count = sum(count))
```

```{r write childes noun}
write.table(noun_freq, file = here("data/processed/childes_noun_freq_vrd.txt"), sep = " ",
            row.names = FALSE, quote = FALSE)
```

```{r read-childes verb} 
verb_freq <- map_dfr(pull(vrd_verbs, word),
        ~get_types(collection = c("Eng-NA", "Eng-UK"), 
                   role_exclude = "Target_Child", 
                                  type = .x)) %>%
  mutate(gloss = tolower(gloss)) %>%
  group_by(gloss) %>%
  summarise(count = sum(count))
```

```{r write childes verb}
write.table(verb_freq, file = here("data/processed/childes_verb_freq_vrd.txt"), sep = " ",
            row.names = FALSE, quote = FALSE)
```

## Get Wordbank Nouns and Verbs

```{r}
wordbank_nouns<-get_item_data(language = "English (American)", form = "WS") %>% filter(lexical_class=="nouns")
wordbank_verbs<-get_item_data(language = "English (American)", form = "WS") %>% filter(lexical_class=="verbs")
```

## Word Set Intersection

```{r}
intersect_noun_list<-intersect(vrd_nouns$word,wordbank_nouns$uni_lemma)
intersect_noun_ids<-subset(wordbank_nouns,uni_lemma %in% intersect_noun_list)$item_id
intersect_nouns<-get_instrument_data(language = "English (American)",
                                   form = "WS",
                                   items = intersect_noun_ids,
                                   administrations = TRUE)
# intersect_nouns
```

```{r}
intersect_verb_list<-intersect(vrd_verbs$word,wordbank_verbs$uni_lemma)
intersect_verb_ids<-subset(wordbank_verbs,uni_lemma %in% intersect_verb_list)$item_id
intersect_verbs<-get_instrument_data(language = "English (American)",
                                   form = "WS",
                                   items = intersect_verb_ids,
                                   administrations = TRUE)
# intersect_verbs
```

## Estimate AoA

```{r}
noun_aoa_data_drop_na<-fit_aoa(intersect_nouns) %>% drop_na(aoa)
noun_aoa_data<- data.frame(word=subset(wordbank_nouns, num_item_id %in% noun_aoa_data_drop_na$num_item_id)$uni_lemma,aoa=noun_aoa_data_drop_na$aoa)
# noun_aoa_data
write.table(arrange(noun_aoa_data,aoa), file = here("data/processed/wordbank_noun_aoa_vrd.txt"), sep = " ",
            row.names = FALSE, quote = FALSE)
```

```{r}
verb_aoa_data_drop_na<-fit_aoa(intersect_verbs) %>% drop_na(aoa)
verb_aoa_data<- data.frame(word=subset(wordbank_verbs, num_item_id %in% verb_aoa_data_drop_na$num_item_id)$uni_lemma,aoa=verb_aoa_data_drop_na$aoa)
# verb_aoa_data
write.table(arrange(verb_aoa_data,aoa), file = here("data/processed/wordbank_verb_aoa_vrd.txt"), sep = " ",
            row.names = FALSE, quote = FALSE)
```

